# Generated by Django 4.1 on 2022-08-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.URLField(blank=True, help_text='Google maps link for the location', null=True)),
                ('max_player_capacity', models.PositiveSmallIntegerField()),
                ('max_spectator_capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='(Untitled)', max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('current_player_capacity', models.PositiveSmallIntegerField()),
                ('current_spectator_capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.arena')),
            ],
        ),
        migrations.AddField(
            model_name='arena',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.sport'),
        ),
    ]
