# Generated by Django 4.1 on 2022-08-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='cover_picture',
            field=models.ImageField(blank=True, editable=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='slot',
            name='current_player_capacity',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
