# Generated by Django 4.1 on 2022-08-28 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('slots', '0005_booking_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_text', models.TextField()),
                ('rating_time', models.DateTimeField(auto_now_add=True)),
                ('rating_update_time', models.DateTimeField(auto_now=True)),
                ('rating_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.sport')),
            ],
        ),
        migrations.CreateModel(
            name='RatingParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('parameter', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='ArenaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_text', models.TextField()),
                ('rating_time', models.DateTimeField(auto_now_add=True)),
                ('rating_update_time', models.DateTimeField(auto_now=True)),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slots.arena')),
                ('rating_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
