# Generated by Django 4.1 on 2022-08-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0006_sportrating_ratingparameter_arenarating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arenarating',
            old_name='rating_text',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='ratingparameter',
            name='is_required',
        ),
    ]
