# Generated by Django 4.1 on 2022-08-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0007_rename_rating_text_arenarating_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportrating',
            old_name='rating_text',
            new_name='comments',
        ),
    ]
